export enum Status {
    PENDING = "PENDING",
    NEW = "NEW",
    ACCEPTED = "ACCEPTED",
    CANCELLED = "CANCELLED",
    PREPARING = "PREPARING",
    PREPARED = "PREPARED",
    DELIVERING = "DELIVERING",
    DELIVERED = "DELIVERED",
    COMPLETED = "COMPLETED",
}
